# Generated by Django 4.1.1 on 2022-10-03 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_app', '0004_reviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
