# Generated by Django 4.1.1 on 2022-10-03 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_app', '0005_rename_reviews_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Watchlist',
            new_name='watchlist',
        ),
    ]
